/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;
import interfaces.JDBC;
import java.awt.*;
import java.math.MathContext;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.*;

/**
 *
 * @author User
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }
    JDBC db=new JDBC();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JLabel();
        btn_minimize = new javax.swing.JLabel();
        comboselect = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Cordia New", 0, 70)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 70, 200, 60);

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Hospital employee details and shedule management automation system ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 130, 450, 14);

        username.setBackground(new java.awt.Color(240, 240, 240));
        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setText("Username");
        username.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        username.setOpaque(false);
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameMouseClicked(evt);
            }
        });
        jPanel1.add(username);
        username.setBounds(190, 200, 220, 30);

        password.setBackground(new java.awt.Color(240, 240, 240));
        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setText("jPasswordField1");
        password.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        password.setOpaque(false);
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
        });
        jPanel1.add(password);
        password.setBounds(190, 250, 220, 30);

        btn_login.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btn_log.png"))); // NOI18N
        btn_login.setBorder(null);
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login.setOpaque(false);
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_loginMouseClicked(evt);
            }
        });
        jPanel1.add(btn_login);
        btn_login.setBounds(420, 200, 60, 80);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Forgot Password");
        jLabel4.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(250, 290, 120, 30);

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/close2.png"))); // NOI18N
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });
        jPanel1.add(btn_exit);
        btn_exit.setBounds(590, 10, 20, 20);

        btn_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Minimize-Window-5122222.png"))); // NOI18N
        btn_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minimizeMouseClicked(evt);
            }
        });
        jPanel1.add(btn_minimize);
        btn_minimize.setBounds(560, 10, 20, 20);

        comboselect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "admin", "employee\t" }));
        comboselect.setOpaque(false);
        jPanel1.add(comboselect);
        comboselect.setBounds(190, 160, 220, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/navigation1.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 620, 350);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(620, 347));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseClicked
         username.setText("");
    }//GEN-LAST:event_usernameMouseClicked

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
         password.setText("");
    }//GEN-LAST:event_passwordMouseClicked

    private void btn_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseClicked
    int response = JOptionPane.showConfirmDialog(null, "Do you want to log this HMS system");
        if (response==0) {
            
                                                  
        try {
            if (comboselect.getSelectedItem()=="admin") {
                logincheck_admin();
                Main.txt_user_category.setText(comboselect.getSelectedItem().toString());
                Main.LogedUser_Label.setText(this.username.getText());
            }  
            else {
               logincheck();
               Main.txt_user_category.setText(comboselect.getSelectedItem().toString());
               Main.LogedUser_Label.setText( this.username.getText());
                
            }
        } catch (Exception e) {
        }
        }
        else
        {
            this.username.setText("");
            this.password.setText("");
        }
    
    }//GEN-LAST:event_btn_loginMouseClicked

    private  void loged_User()
    {
        Main mainForm= new Main();
        Main.LogedUser_Label.setText(this.username.getText());
    }
    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_exitMouseClicked

    private void btn_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeMouseClicked
        setExtendedState(getExtendedState()|login.ICONIFIED );
    }//GEN-LAST:event_btn_minimizeMouseClicked

    private void logincheck()
    {
         if(username.getText().trim().length() == 0 | password.getText().trim().length() == 0){
        JOptionPane.showMessageDialog(null,"User name or password cannot be blank","error",0);
    }else{
        try{
            ResultSet rs = new JDBC().getData("Select Username from login where Username = '"+username.getText()+"'");
            Vector v = new Vector();
            while(rs.next()){
                v.add(rs.getString("Username"));
            
            }
            if(v.isEmpty()){
                JOptionPane.showMessageDialog(null,"Invalid username & password","error",0);
            }else{
                ResultSet rs1 = new JDBC().getData("Select * from login where Username = '"+username.getText()+"'");
               
                while(rs1.next()){
                    if(username.getText().equalsIgnoreCase(rs1.getString("Username")) && password.getText().equals(rs1.getString("password"))){
                    
                    
                    new Main().setVisible(true);
                    this.dispose();
                    }else{
                        JOptionPane.showMessageDialog(null,"Username or password cannot be blank","error",0);
                    }
                }
            }
        }catch(Exception e){
            
        }
            
        
    }

    }
      
    private void logincheck_admin()
    {
         if(username.getText().trim().length() == 0 | password.getText().trim().length() == 0){
        JOptionPane.showMessageDialog(null,"User name or password cannot be blank","error",0);
    }else{
        try{
            ResultSet rs = new JDBC().getData("Select adminUname from administrator where adminUname = '"+username.getText()+"'");
            Vector v = new Vector();
            while(rs.next()){
                v.add(rs.getString("adminUname"));
            
            }
            if(v.isEmpty()){
                JOptionPane.showMessageDialog(null,"Invalid username & password","error",0);
            }else{
                ResultSet rs1 = new JDBC().getData("Select * from administrator where adminUname = '"+username.getText()+"'");
               
                while(rs1.next()){
                    if(username.getText().equalsIgnoreCase(rs1.getString("adminUname")) && password.getText().equals(rs1.getString("adminPass"))){
                    
                    new Main().setVisible(true);
                    this.dispose();
                    }else{
                        JOptionPane.showMessageDialog(null,"Username or password cannot be blank","error",0);
                    }
                }
            }
        }catch(Exception e){
            
        }
            
        
    }

    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_exit;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel btn_minimize;
    private javax.swing.JComboBox comboselect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
