/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import javax.swing.*;
import java.awt.*;
import java.awt.FlowLayout;



/**
 *
 * @author User
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Main() {
        initComponents();
        loadLogin();
        strtup_disable();
        Customcuror();
        
    }
    private void load_emp()
    {
        Nurses_Registration emp_reg= new Nurses_Registration();
        if(emp_reg==null)
        {
            emp_reg = new  Nurses_Registration();
        }
        emp_reg.setVisible(true);
        emp_reg.setSize(1111, 618);
        jDesktopPane2_loadFunction.removeAll();
        jDesktopPane2_loadFunction.add((Component)emp_reg);
    }
    
    private  void createchedule()
    {
        ScheduleCreate empschedule= new ScheduleCreate();
        if(empschedule== null)
        {
            empschedule= new ScheduleCreate();
        }
        empschedule.setVisible(true);
        empschedule.setSize(1111, 618);
        jDesktopPane2_loadFunction.removeAll();
        jDesktopPane2_loadFunction.add((Component) empschedule);
    }
    
     private void load_emp_doctors()
    {
        Doctor_Registration emp_reg= new Doctor_Registration();
        if(emp_reg==null)
        {
            emp_reg = new  Doctor_Registration();
        }
        emp_reg.setVisible(true);
        emp_reg.setSize(1111, 618);
        jDesktopPane2_loadFunction.removeAll();
        jDesktopPane2_loadFunction.add((Component)emp_reg); 
    }
     
     private void load_emp_attendents()
    {
        Attendent_Registration emp_reg= new Attendent_Registration();
        if(emp_reg==null)
        {
            emp_reg = new  Attendent_Registration();
        }
        emp_reg.setVisible(true);
        emp_reg.setSize(1111, 618);
        jDesktopPane2_loadFunction.removeAll();
        jDesktopPane2_loadFunction.add((Component)emp_reg); 
    }
    
     private void load_emp_labor()
    {
        Labor_Registration emp_reg= new Labor_Registration();
        if(emp_reg==null)
        {
            emp_reg = new  Labor_Registration();
        }
        emp_reg.setVisible(true);
        emp_reg.setSize(1111, 618);
        jDesktopPane2_loadFunction.removeAll();
        jDesktopPane2_loadFunction.add((Component)emp_reg); 
    } 
     
    
     private void load_emp_other()
    {
        other_Registration emp_reg= new other_Registration();
        if(emp_reg==null)
        {
            emp_reg = new  other_Registration();
        }
        emp_reg.setVisible(true);
        emp_reg.setSize(1111, 618);
        jDesktopPane2_loadFunction.removeAll();
        jDesktopPane2_loadFunction.add((Component)emp_reg); 
    }  
     
      private void load_emp_OT()
    {
        OverTime emp_reg= new OverTime();
        if(emp_reg==null)
        {
            emp_reg = new  OverTime();
        }
        emp_reg.setVisible(true);
        emp_reg.setSize(1111, 618);
        jDesktopPane2_loadFunction.removeAll();
        jDesktopPane2_loadFunction.add((Component)emp_reg); 
    }  
    private  void loadLogin()
    {
        
    }
    private  void strtup_disable()
    {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2_loadFunction = new javax.swing.JDesktopPane();
        btn_exit = new javax.swing.JLabel();
        btn_minimize = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bottomline_image = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Btn_Doc_Reg = new javax.swing.JLabel();
        Btn_nurse_Reg = new javax.swing.JLabel();
        Btn_attendent_Reg = new javax.swing.JLabel();
        Btn_lebour_Reg = new javax.swing.JLabel();
        Btn_other_Reg = new javax.swing.JLabel();
        LogedUser_Label = new javax.swing.JLabel();
        txt_user_category = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Btn_create_schedule = new javax.swing.JLabel();
        Btn_create_OT = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1306, 710));
        setType(java.awt.Window.Type.POPUP);

        javax.swing.GroupLayout jDesktopPane2_loadFunctionLayout = new javax.swing.GroupLayout(jDesktopPane2_loadFunction);
        jDesktopPane2_loadFunction.setLayout(jDesktopPane2_loadFunctionLayout);
        jDesktopPane2_loadFunctionLayout.setHorizontalGroup(
            jDesktopPane2_loadFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1111, Short.MAX_VALUE)
        );
        jDesktopPane2_loadFunctionLayout.setVerticalGroup(
            jDesktopPane2_loadFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/close2.png"))); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });

        btn_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Minimize-Window-5122222.png"))); // NOI18N
        btn_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minimizeMouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bgtop.png"))); // NOI18N

        bottomline_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bottomline.png"))); // NOI18N

        jLabel1.setText("jLabel1");

        Btn_Doc_Reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/MenuButton.png"))); // NOI18N
        Btn_Doc_Reg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Doc_RegMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_Doc_RegMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_Doc_RegMouseExited(evt);
            }
        });

        Btn_nurse_Reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/MenuButton_nurse.png"))); // NOI18N
        Btn_nurse_Reg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_nurse_RegMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_nurse_RegMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_nurse_RegMouseExited(evt);
            }
        });

        Btn_attendent_Reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/MenuButton_attendent.png"))); // NOI18N
        Btn_attendent_Reg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_attendent_RegMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_attendent_RegMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_attendent_RegMouseExited(evt);
            }
        });

        Btn_lebour_Reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/MainButton_lebourers.png"))); // NOI18N
        Btn_lebour_Reg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_lebour_RegMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_lebour_RegMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_lebour_RegMouseExited(evt);
            }
        });

        Btn_other_Reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/MainButton_other.png"))); // NOI18N
        Btn_other_Reg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_other_RegMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_other_RegMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_other_RegMouseExited(evt);
            }
        });

        LogedUser_Label.setBackground(new java.awt.Color(255, 255, 255));
        LogedUser_Label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LogedUser_Label.setForeground(new java.awt.Color(255, 0, 0));
        LogedUser_Label.setText("User");

        txt_user_category.setBackground(new java.awt.Color(0, 0, 0));
        txt_user_category.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_user_category.setForeground(new java.awt.Color(255, 255, 255));
        txt_user_category.setText("user catgory");
        txt_user_category.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Loged User :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Current User :");

        Btn_create_schedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnschedule.png"))); // NOI18N
        Btn_create_schedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_create_scheduleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_create_scheduleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_create_scheduleMouseExited(evt);
            }
        });

        Btn_create_OT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/OT_H.png"))); // NOI18N
        Btn_create_OT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_create_OTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_create_OTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_create_OTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_Doc_Reg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_nurse_Reg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_attendent_Reg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_lebour_Reg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_other_Reg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LogedUser_Label)
                            .addComponent(txt_user_category)))
                    .addComponent(Btn_create_schedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_create_OT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(Btn_Doc_Reg, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_nurse_Reg, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_attendent_Reg, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_lebour_Reg, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_other_Reg, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_create_schedule, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_create_OT, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_user_category)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogedUser_Label)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 0, 51));
        jMenuBar1.setBorder(null);

        jMenu1.setBackground(new java.awt.Color(0, 153, 255));
        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bottomline_image, javax.swing.GroupLayout.PREFERRED_SIZE, 1313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(22, 22, 22)
                            .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jDesktopPane2_loadFunction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDesktopPane2_loadFunction)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bottomline_image, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_exitMouseClicked

    private void btn_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeMouseClicked
        setExtendedState(getExtendedState()|Main.ICONIFIED );
    }//GEN-LAST:event_btn_minimizeMouseClicked

    private void Btn_Doc_RegMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Doc_RegMouseEntered
        ImageIcon ii = new ImageIcon(getClass().getResource("/resources/MainButtonHover.png"));
        Btn_Doc_Reg.setIcon(ii);
    }//GEN-LAST:event_Btn_Doc_RegMouseEntered

    private void Btn_Doc_RegMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Doc_RegMouseExited
        ImageIcon ii = new ImageIcon(getClass().getResource("/resources/MenuButton.png"));
        Btn_Doc_Reg.setIcon(ii);
    }//GEN-LAST:event_Btn_Doc_RegMouseExited

    private void Btn_nurse_RegMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_nurse_RegMouseEntered
         ImageIcon ii = new ImageIcon(getClass().getResource("/resources/MainButtonHover_nurse.png"));
        Btn_nurse_Reg.setIcon(ii);
    }//GEN-LAST:event_Btn_nurse_RegMouseEntered

    private void Btn_nurse_RegMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_nurse_RegMouseExited
        ImageIcon ii = new ImageIcon(getClass().getResource("/resources/MenuButton_nurse.png"));
        Btn_nurse_Reg.setIcon(ii);
    }//GEN-LAST:event_Btn_nurse_RegMouseExited

    private void Btn_attendent_RegMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_attendent_RegMouseEntered
        ImageIcon ii = new ImageIcon(getClass().getResource("/resources/MainButtonHover_attendent.png"));
        Btn_attendent_Reg.setIcon(ii);
    }//GEN-LAST:event_Btn_attendent_RegMouseEntered

    private void Btn_attendent_RegMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_attendent_RegMouseExited
        ImageIcon ii = new ImageIcon(getClass().getResource("/resources/MenuButton_attendent.png"));
        Btn_attendent_Reg.setIcon(ii);
    }//GEN-LAST:event_Btn_attendent_RegMouseExited

    private void Btn_Doc_RegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Doc_RegMouseClicked
        load_emp_doctors();        
    }//GEN-LAST:event_Btn_Doc_RegMouseClicked

    private void Btn_nurse_RegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_nurse_RegMouseClicked
        load_emp();
    }//GEN-LAST:event_Btn_nurse_RegMouseClicked

    private void Btn_lebour_RegMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_lebour_RegMouseEntered
        ImageIcon ii = new ImageIcon(getClass().getResource("/resources/MainButtonHover_lebourers.png"));
        Btn_lebour_Reg.setIcon(ii);
    }//GEN-LAST:event_Btn_lebour_RegMouseEntered

    private void Btn_lebour_RegMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_lebour_RegMouseExited
       ImageIcon ii = new ImageIcon(getClass().getResource("/resources/MainButton_lebourers.png"));
        Btn_lebour_Reg.setIcon(ii);
    }//GEN-LAST:event_Btn_lebour_RegMouseExited

    private void Btn_other_RegMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_other_RegMouseEntered
        ImageIcon ii = new ImageIcon(getClass().getResource("/resources/MainButtonHover_other.png"));
        Btn_other_Reg.setIcon(ii);
    }//GEN-LAST:event_Btn_other_RegMouseEntered

    private void Btn_other_RegMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_other_RegMouseExited
        ImageIcon ii = new ImageIcon(getClass().getResource("/resources/MainButton_other.png"));
        Btn_other_Reg.setIcon(ii);
    }//GEN-LAST:event_Btn_other_RegMouseExited
   
    private void Btn_create_scheduleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_create_scheduleMouseEntered
        ImageIcon ii = new ImageIcon(getClass().getResource("/resources/btnscheduleHover.png"));
        Btn_create_schedule.setIcon(ii);
    }//GEN-LAST:event_Btn_create_scheduleMouseEntered

    private void Btn_create_scheduleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_create_scheduleMouseExited
        ImageIcon ii = new ImageIcon(getClass().getResource("/resources/btnschedule.png"));
        Btn_create_schedule.setIcon(ii);
    }//GEN-LAST:event_Btn_create_scheduleMouseExited

    private void Btn_create_scheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_create_scheduleMouseClicked
        createchedule();
    }//GEN-LAST:event_Btn_create_scheduleMouseClicked

    private void Btn_attendent_RegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_attendent_RegMouseClicked
        load_emp_attendents();
    }//GEN-LAST:event_Btn_attendent_RegMouseClicked

    private void Btn_lebour_RegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_lebour_RegMouseClicked
        load_emp_labor();
    }//GEN-LAST:event_Btn_lebour_RegMouseClicked

    private void Btn_other_RegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_other_RegMouseClicked
        load_emp_other();
    }//GEN-LAST:event_Btn_other_RegMouseClicked

    private void Btn_create_OTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_create_OTMouseClicked
        load_emp_OT();
    }//GEN-LAST:event_Btn_create_OTMouseClicked

    private void Btn_create_OTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_create_OTMouseEntered
        ImageIcon ii = new ImageIcon(getClass().getResource("/resources/OT.png"));
        Btn_create_OT.setIcon(ii);
    }//GEN-LAST:event_Btn_create_OTMouseEntered

    private void Btn_create_OTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_create_OTMouseExited
        ImageIcon ii = new ImageIcon(getClass().getResource("/resources/OT_H.png"));
        Btn_create_OT.setIcon(ii);
    }//GEN-LAST:event_Btn_create_OTMouseExited

    public void Customcuror()
    {
        Toolkit toolkit= Toolkit.getDefaultToolkit();
        Image img=toolkit.getImage("cursor.png");
        Point point= new Point(0, 0);
        Cursor cursor= toolkit.createCustomCursor(img, point,"Cursor");
        setCursor(cursor);
        
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Btn_Doc_Reg;
    private javax.swing.JLabel Btn_attendent_Reg;
    private javax.swing.JLabel Btn_create_OT;
    private javax.swing.JLabel Btn_create_schedule;
    private javax.swing.JLabel Btn_lebour_Reg;
    private javax.swing.JLabel Btn_nurse_Reg;
    private javax.swing.JLabel Btn_other_Reg;
    public static javax.swing.JLabel LogedUser_Label;
    private javax.swing.JLabel bottomline_image;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JLabel btn_minimize;
    private javax.swing.JDesktopPane jDesktopPane2_loadFunction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel txt_user_category;
    // End of variables declaration//GEN-END:variables
}
