/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class ScheduleCreate extends javax.swing.JPanel {
    JDBC db=new JDBC();
    int sr;
    /**
     * Creates new form ScheduleCreate
     */
    
    public ScheduleCreate() {
        initComponents();
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tablemain = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtEid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        txtdesig = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JcomboShift = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        JcomboTime = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtsearchbyname = new javax.swing.JTextField();
        btnSearch = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        date_search_chooser = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        JSchedule_Date = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        Jtable_schedule = new javax.swing.JTable();
        scheduleID = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btncheck = new javax.swing.JButton();

        Tablemain.setBackground(new java.awt.Color(75, 73, 73));
        Tablemain.setForeground(new java.awt.Color(255, 255, 255));
        Tablemain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Employee ID", "First Name", "Last Name", "Designation"
            }
        ));
        Tablemain.setGridColor(new java.awt.Color(255, 255, 255));
        Tablemain.setSelectionBackground(new java.awt.Color(255, 5, 43));
        Tablemain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablemainMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tablemain);

        jLabel1.setText("Employee ID");

        txtEid.setEditable(false);

        jLabel2.setText("First Name");

        jLabel3.setText("Designation");

        txtFname.setEditable(false);

        txtdesig.setEditable(false);

        jLabel4.setText("Shift");

        JcomboShift.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Shift", "Night Shift", "Morning Shift" }));
        JcomboShift.setPreferredSize(new java.awt.Dimension(88, 25));
        JcomboShift.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JcomboShiftItemStateChanged(evt);
            }
        });

        jLabel5.setText("Time");

        JcomboTime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Time" }));
        JcomboTime.setPreferredSize(new java.awt.Dimension(88, 25));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setText("Create Schedule");
        jButton1.setMargin(new java.awt.Insets(2, 14, 2, 6));
        jButton1.setOpaque(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel6.setFont(new java.awt.Font("Trajan Pro 3", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Check Schedule");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
        );

        txtsearchbyname.setBackground(new java.awt.Color(239, 237, 237));
        txtsearchbyname.setForeground(new java.awt.Color(243, 70, 6));
        txtsearchbyname.setText("Search nurses by name.........");
        txtsearchbyname.setBorder(null);
        txtsearchbyname.setOpaque(false);
        txtsearchbyname.setPreferredSize(new java.awt.Dimension(148, 15));
        txtsearchbyname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtsearchbynameMouseClicked(evt);
            }
        });
        txtsearchbyname.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtsearchbynamePropertyChange(evt);
            }
        });
        txtsearchbyname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsearchbynameKeyTyped(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("     Search");
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search.png"))); // NOI18N

        date_search_chooser.setBackground(new java.awt.Color(0, 0, 0));
        date_search_chooser.setForeground(new java.awt.Color(255, 255, 255));
        date_search_chooser.setDateFormatString("yyyy-MM-dd");
        date_search_chooser.setOpaque(false);

        jLabel7.setText("Date");

        JSchedule_Date.setDateFormatString("yyyy-MM-dd");

        Jtable_schedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "First Name", "Last Name", "Date", "Designation", "Shift", "Time"
            }
        ));
        jScrollPane2.setViewportView(Jtable_schedule);

        scheduleID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        scheduleID.setText("Schedule ID");

        jLabel8.setText("Find the schedule specific day");

        btncheck.setText("Check");
        btncheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncheckMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date_search_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncheck, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEid, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JSchedule_Date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JcomboShift, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtdesig, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(JcomboTime, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtsearchbyname, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scheduleID)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtsearchbyname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(scheduleID)
                        .addGap(21, 21, 21)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtEid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdesig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JSchedule_Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JcomboShift, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel7))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(5, 5, 5))
                            .addComponent(JcomboTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(7, 7, 7)
                        .addComponent(date_search_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncheck)))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtsearchbynameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsearchbynameMouseClicked
        this.txtsearchbyname.setText("");
    }//GEN-LAST:event_txtsearchbynameMouseClicked

    private void txtsearchbynamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtsearchbynamePropertyChange

    }//GEN-LAST:event_txtsearchbynamePropertyChange

    private void txtsearchbynameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchbynameKeyTyped
        filterTableValue_by_name();
    }//GEN-LAST:event_txtsearchbynameKeyTyped

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        SearchForButton();
    }//GEN-LAST:event_btnSearchMouseClicked

    private void TablemainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablemainMouseClicked
        retriveValFromTable();
        auto_gen_id();
    }//GEN-LAST:event_TablemainMouseClicked

    private void JcomboShiftItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JcomboShiftItemStateChanged
        shiftSelect();
        auto_gen_id();
        
        
    }//GEN-LAST:event_JcomboShiftItemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        addSchedule();
    }//GEN-LAST:event_jButton1MouseClicked

    private void btncheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncheckMouseClicked
        CheckScheduleByDate();
    }//GEN-LAST:event_btncheckMouseClicked

    
    private  void filterTableValue_by_name()
    {
     
        if ("".equals(txtsearchbyname.getText())) {
            while (Tablemain.getRowCount() > 0) {
            ((DefaultTableModel)Tablemain.getModel()).removeRow(0);
            }
        }
        else{
            while (Tablemain.getRowCount() > 0) {
            ((DefaultTableModel)Tablemain.getModel()).removeRow(0);
            }


            try {
                DefaultTableModel dtm = (DefaultTableModel) Tablemain.getModel();
                ResultSet r = db.getData("select employee.E_id,employee.Efname,employee.Elname,designation.desig from employee join designation on employee.E_id = designation.E_id where employee.Efname like '"+txtsearchbyname.getText()+"%' or  employee.NIC like '"+txtsearchbyname.getText()+"%' or employee.E_id like '"+txtsearchbyname.getText()+"%' or designation.desig like '"+txtsearchbyname.getText()+"%'");

                while (r.next()) {
                Vector v = new Vector();
                v.add(r.getString("E_id"));
                v.add(r.getString("Efname"));
                v.add(r.getString("Elname"));
                v.add(r.getString("desig"));


                dtm.addRow(v);

            }
            } catch (Exception e) {
            }
        }
    }
    
    private void retriveValFromTable()
    {
        try {
            sr=Tablemain.getSelectedRow();
            DefaultTableModel dtm=(DefaultTableModel)Tablemain.getModel();
            
            String Eid=(String) dtm.getValueAt(sr, 0);
            String fname=(String) dtm.getValueAt(sr,1);
            //String lname=(String) dtm.getValueAt(sr, 2);
            String desig=(String) dtm.getValueAt(sr, 3);
            
            this.txtEid.setText(Eid);
            this.txtFname.setText(fname);
            this.txtdesig.setText(desig);
        } catch (Exception e) {
        }
        shiftSelect();
    }
    
    private void SearchForButton()
    {
        try{
        ResultSet rs=new JDBC().getData("select employee.E_id,employee.Efname,employee.Elname,designation.desig from employee join designation on employee.E_id = designation.E_id where employee.E_id='"+ this.txtsearchbyname.getText()+"'");
        while(rs.next()){
        txtEid.setText(rs.getString("E_id"));
        txtFname.setText(rs.getString("Efname"));
        //txtlname.setText(rs.getString("Elname"));
        
        txtdesig.setText(rs.getString("desig"));
        }
        }catch(Exception e){
            System.out.println(e);
        }
    }
    
    private void shiftSelect()
    {
        int itemCount = JcomboTime.getItemCount();
        try {
            if ("Doctor".equals(txtdesig.getText())) {
                
                for(int i=0;i<itemCount;i++){
                JcomboTime.removeItemAt(0);
     }
                this.JcomboTime.addItem("8:00am-2:00pm");
                this.JcomboTime.addItem("2:00pm-8:00pm");
                this.JcomboTime.addItem("8:00pm-2:00am");
                this.JcomboTime.addItem("2:00am-8:00am");
                
            } 
            else if ("Nurse".equals(txtdesig.getText()))
            {
                for(int i=0;i<itemCount;i++){
                JcomboTime.removeItemAt(0);
                }
                this.JcomboTime.addItem("8:00am-4:00pm");
                this.JcomboTime.addItem("4:00pm-12:00am");
                this.JcomboTime.addItem("12:00am-8:00am");
            }
            else if ("attendants".equals(txtdesig.getText()))
            {
                for(int i=0;i<itemCount;i++){
                JcomboTime.removeItemAt(0);
                }
                this.JcomboTime.addItem("8:00am-4:00pm");
                this.JcomboTime.addItem("4:00pm-12:00am");
                this.JcomboTime.addItem("12:00am-8:00am");
            }
            else if ("labourers".equals(txtdesig.getText()))
            {
                for(int i=0;i<itemCount;i++){
                JcomboTime.removeItemAt(0);
                }
                this.JcomboTime.addItem("8:00am-4:00pm");
                this.JcomboTime.addItem("4:00pm-12:00am");
                this.JcomboTime.addItem("12:00am-8:00am");
            }
            else if ("OtherAnyEmployers".equals(txtdesig.getText()))
            {
                for(int i=0;i<itemCount;i++){
                JcomboTime.removeItemAt(0);
                }
                this.JcomboTime.addItem("8:00am-4:00pm");
                this.JcomboTime.addItem("4:00pm-12:00am");
                this.JcomboTime.addItem("12:00am-8:00am");
            }
            else {
            }
        } catch (Exception e) {
        }
    }
    
    private void addSchedule()
    {
        String id=txtEid.getText();
        String Sid=scheduleID.getText();
        DateFormat get_date1=new SimpleDateFormat("yyyy-MM-dd");
        String Jdate1 = get_date1.format(JSchedule_Date.getDate());
        String Eshift= JcomboShift.getSelectedItem().toString();
        String Etime= JcomboTime.getSelectedItem().toString();
        
        try {
            db.putData("insert into empshedule(Shedule_id,E_id,Date,WorkingHour,Shift)values('"+ Sid+"','"+id+"','"+Jdate1+"','"+Etime+"','"+Eshift+"')");
            //insertdesination();
            JOptionPane.showMessageDialog(null,"Insert Successfully","",JOptionPane.PLAIN_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Something Wrong","",JOptionPane.ERROR_MESSAGE);
        }
    }
    
//    private  void insertdesination()
//    {
//        String id=scheduleID.getText();
//        String Eshift= JcomboShift.getSelectedItem().toString();
//        
//        try {
//            db.putData("insert into empshift (Shedule_id,Shift) values ('"+ id +"','"+  Eshift +"')");
//        } catch (Exception e) {
//        }
//    }
    
    private  void auto_gen_id()
    {
       try {
            ResultSet r = db.getData("SELECT MAX(Shedule_id)from empshedule where Shedule_id like '1%' ");
            while (r.next()) {
            String id = r.getString(1);
            int maxid=Integer.parseInt(id);
            String maxval=Integer.toString(maxid+1);
            scheduleID.setText(maxval);
  
        }
        } catch (Exception ex) {
            Logger.getLogger(Nurses_Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void CheckScheduleByDate()
    {
        while (Jtable_schedule.getRowCount() > 0) {
	((DefaultTableModel)Jtable_schedule.getModel()).removeRow(0);
        }
        DateFormat get_date=new SimpleDateFormat("yyyy-MM-dd");
        String Jdate1 = get_date.format(date_search_chooser.getDate());
        
        try {
            DefaultTableModel dtm = (DefaultTableModel) Jtable_schedule.getModel();
            ResultSet r = db.getData("select employee.E_id,employee.Efname,employee.Elname,empshedule.Date,designation.desig,empshedule.Shift,empshedule.WorkingHour from employee LEFT JOIN designation on employee.E_id = designation.E_id LEFT JOIN empshedule on employee.E_id=empshedule.E_id where empshedule.Date='"+ Jdate1+"' ");
            
            while (r.next()) {
            Vector v = new Vector();
            v.add(r.getString("E_id"));
            v.add(r.getString("Efname"));
            v.add(r.getString("Elname"));
            v.add(r.getString("desig"));
            v.add(r.getString("Date"));
            v.add(r.getString("Shift"));
            v.add(r.getString("WorkingHour"));
            
            

            dtm.addRow(v);

        }
        } catch (Exception e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JSchedule_Date;
    private javax.swing.JComboBox JcomboShift;
    private javax.swing.JComboBox JcomboTime;
    private javax.swing.JTable Jtable_schedule;
    private javax.swing.JTable Tablemain;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JButton btncheck;
    private com.toedter.calendar.JDateChooser date_search_chooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel scheduleID;
    private javax.swing.JTextField txtEid;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtdesig;
    private javax.swing.JTextField txtsearchbyname;
    // End of variables declaration//GEN-END:variables
}
